### PR TITLE
Arduino shield PCB design

### PR DESCRIPTION
**Pull request by LegacyNsfw**
This is as much a cry for help it is a pull request. I had a PCB made using this file, and it doesn't actually work. If anyone can spot the problem I'll be happy (delighted!) to implement it, validate it, and update the file.

If you're not familiar with Fritzing, it's an open source EDA / schematic / breadboard / PCB layout app that came out of Potsdam University. This is the first project I've done with it, and I've been very impressed with the usability.

https://fritzing.org/
https://github.com/fritzing/fritzing-app

In theory, you can build it yourself; in practice, that's harder than it sounds. They want a small donation to download pre-built installer. After wrestling with QT for a while I gave up and made the donation. Totally worth it, IMO. :-)

### CODE REVIEW

**Comment by LegacyNsfw** [comment]
I'm testing it with a Mega2560. I have it wired up to a General Motors P01 PCM and an OBDLink SX, which are happily sending data back and forth. The signal coming into R5 looks good on my scope, but the signal coming out of R5 / going into T2 is very noisy.

I'm not strong in electronics so I'd appreciate suggestions for troubleshooting.

Thanks!
VpwShield1

**Comment by fredmcc** [comment]
Its sort of hard to tell without seeing the circuit but my guess is you have the collector and emitter reversed on your transistors. At least it looks that way if your using BC548's. If thats the case you can fix it by flipping them around.

**Comment by LegacyNsfw** [comment]
Thanks, I'll give that a shot.

Here's a picture. This was taken after I cut D3 to focus on troubleshooting the input side.

image

**Comment by LegacyNsfw** [comment]
I'm pretty sure the transistor orientations are correct. 

EDT: because I was looking at the wrong image. Here's a correct image:
image


I forgot to mention that there's a trace missing in the photo, which I fixed by adding a wire after the photo was taken. The 'missing' trace is present in the PCB layout image, from the left side of the ground pin in J1 down to the ground pin in the Arduino header.

**Comment by stlnick2** [comment]
What pins are you going for on the mega2560?

**Comment by LegacyNsfw** [comment]
I've tried RX on pin 7 (I designed the shield to use that pin, but don't recall why) and 10 (since the sample code used 10), with a jumper wire on the shield's through-header to connect pins 7 and 10.  

TX on pin 6, but I haven't experimented with that. RX is the higher priority.

I also tried switching the orientation of T2, as per fredmcc's post, but that also didn't make a difference.

**Comment by fredmcc** [comment]
The voltage at the base of T2 is only going to be somewhere between 0 and 0.7V and measuring it might not tell you much. 
Have you connected the scope to the RX pin of the arduino?
Is it getting a solid 5v signal?
Maybe you can insert some pictures of the scope trace at the VPW input and the arduino rx pin.

**Comment by LegacyNsfw** [comment]
I have confirmed with a scope that T2 was backward. At the RX pin I get 0 or +5v, and it matches the shape of the raw VPW line. So with that change I'm confident that the receive path is electrically correct. Now if I can just get the code to work... :)  

Also found that the Mega 2560 only supports attachInterrupt on a few of its pins, and neither 7 or 10 are in the list, so I switched the input to pin 2, and then 3, and then 18... and the sniffer sample app doesn't report any VPW messages either way. (I have a data logger polling continuously on the VPW bus, so the VPW line is quite busy.)

https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/

When tryGetReceivedFrame returns 0, sniffer.ino now does this...
digitalWrite(DEBUG_PIN, digitalRead(RX));
...and that gives me a rough equivalent of the RX in state on an output pin that I've got hooked up to my scope, so I'm confident that the signal is present on the RX pin (the same pin number passed to init(RX)).

I also tried adding this to the J1850VPW class, to see what's happening in the interrupt handler:
uint8_t getCurrentRxPinState() { return _currState; }
But when I do this in the ino file...
digitalWrite(DEBUG_PIN, vpw.getCurrentRxPinState());
...the output pin just goes high and stays high.  So I think the interrupt handler isn't being called, despite the pin state changing.

Thanks for your help, I really appreciate it.

**Comment by LegacyNsfw** [comment]
Top trace: output of T2 / input of RX pin.
Middle trace: the 'debug' pin, digitalWrite(DEBUG_PIN, digitalRead(RX));
Bottom trace: the VPW line.

VPW_Scope

**Comment by LegacyNsfw** [comment]
Something about this library's translation from pin number to interrupt callback doesn't work properly on the Mega 2560. I hacked around it as follows:

I replaced this:
```
void J1850VPWFriend::__handleRnChange(int state, void* pData) {
    ((J1850VPW*)pData)->onRxChaged(state);
}

```
With this:

```
J1850VPW* hackVpw;
int hackPin;
void callback()
{
    hackVpw->onRxChaged(digitalRead(hackPin));
}

```
And replaced this:
`__rxPin.attachInterrupt(PIN_CHANGE_BOTH, &J1850VPWFriend::__handleRnChange, this);`

With this:
```
hackVpw = this;
hackPin = rxPin;
attachInterrupt(digitalPinToInterrupt(rxPin), callback, CHANGE);

```

And my debug pin now reflects the internal state of the vpw object, like this:
`digitalWrite(DEBUG_PIN, vpw.getCurrentRxPinState());`

And it almost works. The scope now shows that the interrupt callback is being invoked and the vpw object is updating __currState. But it also shows a lag in the first state-change of the VPW packet, which of course breaks the VPW state machine.  I'm guessing that lag might be reason the existing VPW code uses the lower-level interrupt API in the first place. 

VpwTrace2

**Comment by fredmcc** [comment]
From what I understand this library works on the pin change interrupt which fires an interrupt when any pin on a port changes.  Its different to the interrupt that happens when you attach an interrupt to a pin which on an ATMEGA328 only gives you 2 pin choices I think. The way this library works it allows for all pins on a 328.
My understanding is a 2560 has a different interrupt strategy and my guess is that is why you're project is not working.

I got this to work on a Teensy which has a completely different interrupt structure. I did it by using the attachInterrupt on the Rx pin.
See code below....

In setup():
attachInterrupt(J1850VPW_RX, j1850RXOnChange, CHANGE);

Seperate ISR in .ino file
void j1850RXOnChange() {
  j1850vpw.onRxChaged(digitalRead(J1850VPW_RX));
}

Cant remember if I changed anything else. But that might give you a good clue.

**Comment by LegacyNsfw** [comment]
I figured out the lag issue, and it was totally self-inflected. Moving the digitalWrite(DEBUG, digitalRead(RX)) call out of the main loop and into the interrupt handler fixed it. The scope now shows exactly the same signal from the debug pin as on the RX pin.

Still not getting VPW message decoding to work though. As far as I can tell, this condition never evaluates to true:

if (_sofRead = (curr == ACTIVE && IS_BETWEEN(diff, RX_SOF_MIN, RX_SOF_MAX)))

The 'diff' value is always longer than RX_SOF_MAX. I haven't had time to investigate why yet. I do have another device on the VPW bus decoding all of the traffic and it's showing the data that I expect it to.

Thanks for bearing with me, and thanks for your help, I really appreciate it.

**Comment by matafonoff** [comment]
Avoid using digitalRead and digitalWrite. These methods are extremely slow. Use Pin class. It has some caching to decrease number of operations that are done.

**Comment by LegacyNsfw** [comment]
The sniffer example is working now. The key thing was to to prevent the handleError callback from using the serial port when J1850_ERR_PULSE_OUTSIDE_FRAME happens. Use of the serial port during the interrupt handler on a Mega 2560 causes micros() to become inaccurate[1] which confuses onRxChanged state-machine. 

This might not be a problem if there is little traffic on the VPW bus, but in my case the VPW bus is very busy, so the Arduino almost always starts listening during the middle of a frame, so it immediately thinks that it found a pulse outside of a frame, so it prints an error, which breaks micros() and prevents it from ever catching up. Suppressing the error report keeps micros() accurate so the code is able to captures the next full message that it hears.

It even works with digitalRead, though I have switched back to the Pin class.

```
    if (err == J1850_ERR_PULSE_OUTSIDE_FRAME)
    {
        return;
    }

```

And there it is:

RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e
RX: 6c 10 f0 2a 01 fe fd 0a
RX: 6c f0 10 6a fe 00 00 00 00 00 0a 43
RX: 6c f0 10 6a fd 00 00 0a 01 01 00 0e

Next up: get the transmit circuit working. Hopefully that will only require flipping the transistors and reconnecting the diode that I clipped, but we'll see. It I can get it working I'll update the PCB file, have another batch made, and update this pull request if it works.

I'll also look for a way to c;lean up the changes that were needed to make this work on my Mega 2560, and submit a separate pull request for that. The fix is pretty ugly right now, but I don't think it needs to be.

[1] https://arduino.stackexchange.com/questions/22212/using-millis-and-micros-inside-an-interrupt-routine

**Comment by LegacyNsfw** [comment]
Flipping the transistors fixed the output side, and I've confirmed with someone at the Fritzing forum that the transistor silkscreen is 180 degrees off. 

I don't know how I missed the transistor problem, but it's so obvious now that I can't un-see it. 

EDIT: Now I know exactly how I missed that problem - I was looking at an image for a different transistor. I've replaced the image that I posted earlier with one that's correct.

**Pull request merged**
